## Numpy

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
b = [3,4,2,3]

c = a + b
c

[1, 2, 3, 4, 3, 4, 2, 3]

In [3]:
type(a)

list

In [4]:
# 1D List --> 1D numpy Array
# 2D List --> 2D numpy Array

In [5]:
a_arr = np.array(a)
a_arr

array([1, 2, 3, 4])

In [6]:
b_arr = np.array(b)
b_arr

array([3, 4, 2, 3])

In [7]:
c_arr = a_arr + b_arr
c_arr

array([4, 6, 5, 7])

In [8]:
multi_d = np.array([
    [1,2,3],
    [5,6,7],
    [8,6,5]
])
multi_d

array([[1, 2, 3],
       [5, 6, 7],
       [8, 6, 5]])

In [9]:
print(a)
print(a_arr)
a_arr
# which of the following is numpy array data ?

[1, 2, 3, 4]
[1 2 3 4]


array([1, 2, 3, 4])

In [10]:
a_arr.shape

(4,)

In [11]:
multi_d.shape

(3, 3)

Zeros and ones

In [12]:
# zeros, ones(shape, dtype = float(default)/int)

In [13]:
zero_1d = np.zeros(10, dtype = int)
zero_1d

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
one_1d = np.ones(10, dtype = int)
one_1d

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
zero_2d = np.zeros((6,5), dtype = int)
zero_2d

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [16]:
one_2d = np.ones((6,5), dtype = int)
one_2d

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Arange

In [17]:
numbers = np.arange(1,50)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
numbers = []
for i in range(1,51):
    numbers.append(i)
numbers = np.array(numbers)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

## Reshape and Ravel

Reshape : Change dimension of an array.<br>
Ravel: Change any dimension of array into 1D array. -------> Flatten

In [19]:
reshape_numbers = numbers.reshape(10,5)
reshape_numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [20]:
flat_number = numbers.reshape(50)
flat_number

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [21]:
ravel_numbers = np.ravel(reshape_numbers)
ravel_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

## Array Broadcasting

'''

1. All shape of arrays must be same.
2. Atleast one array's dimension row/column must be 1 and other must be equal.
3. Array also can be of 1*1 matrix form

'''

In [22]:
md1 = np.array([
    [1,2,3],
    [5,6,7],
    [8,9,10]
])

md2 = np.array([
    [3,2,1],
    [6,8,9],
    [3,7,5]
])

In [23]:
calc = md1 * md2
calc

array([[ 3,  4,  3],
       [30, 48, 63],
       [24, 63, 50]])

## Boolean Indexing

In [24]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [25]:
## Find numbers greater than 50.
numbers > 40

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [26]:
filter_numbers = numbers > 40
numbers[filter_numbers]

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [27]:
filter_num = numbers[numbers > 40]
filter_num

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [28]:
fruits = np.array(['Apple', 123, 'Banana', True, 1.4])
fruits

array(['Apple', '123', 'Banana', 'True', '1.4'], dtype='<U32')

In [29]:
fruits = np.array(['Apple', 'Banana'])
fruits

array(['Apple', 'Banana'], dtype='<U6')

## Slicing

In [30]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [31]:
numbers[4:9]

array([5, 6, 7, 8, 9])

In [32]:
reshape_numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [33]:
for row in reshape_numbers[1:3]:
    print(row[2:])

[ 8  9 10]
[13 14 15]


In [34]:
reshape_numbers[1:3, 2:]

array([[ 8,  9, 10],
       [13, 14, 15]])